import { Product } from "./types";

export const CATEGORIES = [
  "All",
  "Chargers",
  "Cables",
  "Power Banks",
  "Cases & Protection",
  "Audio",
  "Repair Kits",
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "voltcore-65w-gan-charger",
    name: "VoltCore 65W GaN Fast Charger",
    category: "Chargers",
    price: 549,
    compareAtPrice: 699,
    rating: 4.8,
    reviewCount: 214,
    badge: "Bestseller",
    shortDescription: "Compact GaN charger that powers phones, tablets and laptops.",
    description:
      "The VoltCore 65W GaN Fast Charger shrinks desktop-charger power into a block the size of a matchbox. Dual USB-C PD ports intelligently share power across two devices, so you can top up a laptop and a phone at the same time without losing speed. Built-in surge and over-heat protection keeps every device you own safe, night after night.",
    features: [
      "65W USB-C Power Delivery 3.0",
      "Dual-port simultaneous fast charging",
      "GaN technology — 40% smaller than standard chargers",
      "Smart surge, over-current & thermal protection",
      "Compatible with phones, tablets & ultrabooks",
    ],
    icon: "Zap",
    colorway: ["#0a0a0a", "#3a3a3a"],
    inStock: true,
    stockCount: 42,
    sku: "BFL-CHG-065",
  },
  {
    id: "2",
    slug: "linecore-usbc-braided-cable",
    name: "LineCore Braided USB-C Cable 1.2m",
    category: "Cables",
    price: 179,
    rating: 4.7,
    reviewCount: 388,
    badge: "Bestseller",
    shortDescription: "Nylon-braided cable rated for 20,000+ bend cycles.",
    description:
      "Everyday cables fail where you can't see it — inside the connector. LineCore uses a reinforced aramid-fibre core and laser-welded connectors tested to more than 20,000 bend cycles, wrapped in a tangle-resistant nylon braid. Supports 60W fast charging and full-speed data sync.",
    features: [
      "Aramid-fibre reinforced core",
      "60W / 3A fast-charge rated",
      "480Mbps data transfer",
      "20,000+ bend-cycle durability",
      "1.2m length, matte black finish",
    ],
    icon: "Cable",
    colorway: ["#141414", "#2e2e2e"],
    inStock: true,
    stockCount: 130,
    sku: "BFL-CBL-012",
  },
  {
    id: "3",
    slug: "aegis-shield-tempered-glass",
    name: "Aegis Shield Tempered Glass (2-Pack)",
    category: "Cases & Protection",
    price: 149,
    rating: 4.6,
    reviewCount: 502,
    badge: null,
    shortDescription: "9H hardness glass with oleophobic anti-fingerprint coating.",
    description:
      "Aegis Shield is precision cut and edge-polished for a perfect corner-to-corner fit, then treated with an oleophobic coating that resists smudges and fingerprints. Each pack includes an alignment tray for a bubble-free, dust-free install in under a minute.",
    features: [
      "9H hardness — scratch & shatter resistant",
      "Oleophobic anti-fingerprint coating",
      "99% touch sensitivity retained",
      "Bubble-free install tray included",
      "Pack of 2",
    ],
    icon: "ShieldCheck",
    colorway: ["#0a0a0a", "#454545"],
    inStock: true,
    stockCount: 210,
    sku: "BFL-PRO-021",
  },
  {
    id: "4",
    slug: "obsidian-armor-case",
    name: "Obsidian Armor Protective Case",
    category: "Cases & Protection",
    price: 249,
    rating: 4.9,
    reviewCount: 176,
    badge: "New",
    shortDescription: "Military-grade drop protection in a slim matte shell.",
    description:
      "Obsidian Armor pairs a shock-absorbing TPU inner frame with a rigid polycarbonate outer shell, tested to survive 2.4m drops onto concrete. Raised bezels protect the screen and camera, while the soft-touch matte finish stays grip-friendly and smudge-free.",
    features: [
      "MIL-STD-810G drop-tested to 2.4m",
      "Raised camera & screen bezels",
      "Soft-touch matte, non-slip finish",
      "Wireless charging compatible",
      "Available in Jet Black & Slate Grey",
    ],
    icon: "ShieldHalf",
    colorway: ["#000000", "#3f3f3f"],
    inStock: true,
    stockCount: 64,
    sku: "BFL-PRO-044",
  },
  {
    id: "5",
    slug: "corepower-20000-power-bank",
    name: "CorePower 20,000mAh Power Bank",
    category: "Power Banks",
    price: 799,
    compareAtPrice: 949,
    rating: 4.7,
    reviewCount: 260,
    badge: "Sale",
    shortDescription: "22.5W fast-charge power bank with digital display.",
    description:
      "Never run out mid-day. CorePower packs 20,000mAh into a travel-friendly slab with a real-time digital percentage display, three output ports, and 22.5W fast charging that can refill a phone to 50% in about 30 minutes.",
    features: [
      "20,000mAh high-density battery cell",
      "22.5W fast-charge output",
      "Digital percentage display",
      "3 ports — 2x USB-A, 1x USB-C PD",
      "Airline carry-on safe",
    ],
    icon: "BatteryCharging",
    colorway: ["#0a0a0a", "#2b2b2b"],
    inStock: true,
    stockCount: 58,
    sku: "BFL-PWR-200",
  },
  {
    id: "6",
    slug: "corepower-10000-slim",
    name: "CorePower Slim 10,000mAh",
    category: "Power Banks",
    price: 499,
    rating: 4.5,
    reviewCount: 141,
    badge: null,
    shortDescription: "Pocket-sized power bank, 15mm thin.",
    description:
      "Slim enough to disappear in a jacket pocket, CorePower Slim still holds a full 10,000mAh — good for around two extra full charges on most phones — with pass-through charging so you can charge it and your phone from one wall socket overnight.",
    features: [
      "10,000mAh in a 15mm slim body",
      "18W USB-C fast charging",
      "Pass-through charging support",
      "Dual-output for charging two devices",
      "Matte soft-touch finish",
    ],
    icon: "BatteryFull",
    colorway: ["#111111", "#3a3a3a"],
    inStock: true,
    stockCount: 90,
    sku: "BFL-PWR-100",
  },
  {
    id: "7",
    slug: "resonate-anc-earbuds",
    name: "Resonate ANC Wireless Earbuds",
    category: "Audio",
    price: 1199,
    compareAtPrice: 1499,
    rating: 4.8,
    reviewCount: 322,
    badge: "Bestseller",
    shortDescription: "Active noise cancelling earbuds with 32-hour battery life.",
    description:
      "Resonate combines hybrid active noise cancellation with a custom 11mm driver tuned for clear vocals and deep bass. A sealed charging case extends total playtime to 32 hours, and touch controls make skipping tracks or taking calls effortless.",
    features: [
      "Hybrid active noise cancellation",
      "11mm dynamic drivers",
      "32-hour total battery life (case included)",
      "IPX5 sweat & splash resistant",
      "Touch controls + companion app EQ",
    ],
    icon: "Headphones",
    colorway: ["#050505", "#333333"],
    inStock: true,
    stockCount: 37,
    sku: "BFL-AUD-032",
  },
  {
    id: "8",
    slug: "resonate-over-ear",
    name: "Resonate Over-Ear Studio Headphones",
    category: "Audio",
    price: 1799,
    rating: 4.6,
    reviewCount: 98,
    badge: "New",
    shortDescription: "Studio-tuned over-ear headphones with 40-hour battery.",
    description:
      "Memory-foam ear cushions and a folding aluminium frame make Resonate Studio comfortable for all-day wear, while a 40mm driver set delivers a balanced, studio-reference sound signature. Bluetooth 5.3 keeps the connection stable up to 15 metres.",
    features: [
      "40mm studio-tuned drivers",
      "40-hour battery, USB-C quick charge",
      "Bluetooth 5.3, multipoint pairing",
      "Memory-foam cushions, foldable frame",
      "Built-in mic for calls",
    ],
    icon: "Headphones",
    colorway: ["#0a0a0a", "#404040"],
    inStock: true,
    stockCount: 21,
    sku: "BFL-AUD-040",
  },
  {
    id: "9",
    slug: "precision-repair-toolkit",
    name: "Precision 24-Piece Repair Toolkit",
    category: "Repair Kits",
    price: 399,
    rating: 4.9,
    reviewCount: 152,
    badge: "Bestseller",
    shortDescription: "The exact toolkit our technicians use in-store.",
    description:
      "The same 24-piece kit our own repair bench uses daily. Precision bits cover virtually every phone, tablet and laptop screw type, paired with anti-static tools, suction cups and opening picks for safe, scratch-free disassembly.",
    features: [
      "24 precision bits (Pentalobe, Tri-point, Torx & more)",
      "Anti-static ESD-safe tools",
      "Suction cup & spudger set",
      "Compact zip case",
      "Includes step-by-step guide card",
    ],
    icon: "Wrench",
    colorway: ["#0a0a0a", "#484848"],
    inStock: true,
    stockCount: 75,
    sku: "BFL-KIT-024",
  },
  {
    id: "10",
    slug: "cleanpro-screen-kit",
    name: "CleanPro Screen Care Kit",
    category: "Repair Kits",
    price: 129,
    rating: 4.4,
    reviewCount: 87,
    badge: null,
    shortDescription: "Streak-free cleaning kit for screens and cameras.",
    description:
      "A tech-safe cleaning solution and microfibre cloth pair with a soft brush for camera lenses and charging ports, keeping your devices spotless without risking coating damage that household cleaners can cause.",
    features: [
      "Alcohol-free, screen-safe solution",
      "Ultra-fine microfibre cloth",
      "Anti-static soft brush",
      "Safe for coated & anti-glare screens",
      "Travel-friendly 30ml bottle",
    ],
    icon: "Sparkles",
    colorway: ["#141414", "#3a3a3a"],
    inStock: true,
    stockCount: 160,
    sku: "BFL-KIT-030",
  },
  {
    id: "11",
    slug: "magloop-wireless-charger",
    name: "MagLoop Magnetic Wireless Charger",
    category: "Chargers",
    price: 449,
    rating: 4.5,
    reviewCount: 133,
    badge: null,
    shortDescription: "15W magnetic snap-on wireless charging puck.",
    description:
      "MagLoop's ring of magnets snaps into perfect alignment every time, delivering a steady 15W wireless charge with no fumbling for the sweet spot. The braided cable and weighted base keep it stable on any desk or nightstand.",
    features: [
      "15W magnetic wireless charging",
      "Auto-alignment magnet ring",
      "1.5m braided USB-C cable",
      "Weighted non-slip base",
      "Overheat & foreign-object detection",
    ],
    icon: "Magnet",
    colorway: ["#0a0a0a", "#2f2f2f"],
    inStock: true,
    stockCount: 54,
    sku: "BFL-CHG-015",
  },
  {
    id: "12",
    slug: "voltcore-car-charger",
    name: "VoltCore Dual-Port Car Charger",
    category: "Chargers",
    price: 229,
    rating: 4.3,
    reviewCount: 76,
    badge: null,
    shortDescription: "36W dual-port fast charger for your vehicle.",
    description:
      "A low-profile car charger that stays flush with your dashboard socket, delivering up to 36W combined output across two ports so driver and passenger can charge at full speed at the same time.",
    features: [
      "36W combined dual-port output",
      "USB-C PD + USB-A QC 3.0",
      "LED indicator ring",
      "Compact, flush-fit design",
      "Short-circuit & over-current protection",
    ],
    icon: "Car",
    colorway: ["#111111", "#363636"],
    inStock: true,
    stockCount: 88,
    sku: "BFL-CHG-036",
  },
  {
    id: "13",
    slug: "linecore-lightning-cable",
    name: "LineCore Braided Lightning Cable 1m",
    category: "Cables",
    price: 169,
    rating: 4.6,
    reviewCount: 210,
    badge: null,
    shortDescription: "MFi-style braided cable built for daily use.",
    description:
      "Built to the same durability standard as our USB-C line, this Lightning cable adds reinforced strain-relief at both ends — the single most common failure point on stock cables — for a cable that outlasts the phone it came with.",
    features: [
      "Reinforced strain-relief connectors",
      "Fast-charge rated",
      "480Mbps sync speed",
      "1m braided nylon jacket",
      "20,000+ bend-cycle tested",
    ],
    icon: "Cable",
    colorway: ["#0a0a0a", "#333333"],
    inStock: true,
    stockCount: 102,
    sku: "BFL-CBL-013",
  },
  {
    id: "14",
    slug: "linecore-usbc-usbc-2m",
    name: "LineCore USB-C to USB-C Cable 2m",
    category: "Cables",
    price: 199,
    rating: 4.7,
    reviewCount: 164,
    badge: null,
    shortDescription: "Extra-long 100W-rated cable for desk or bedside.",
    description:
      "The extra reach you want beside a bed or under a desk, without giving up charging speed — rated for 100W so it works just as well with a laptop as it does with a phone.",
    features: [
      "100W USB-C PD rated",
      "2m length",
      "480Mbps data transfer",
      "Braided nylon jacket",
      "Reinforced connector housings",
    ],
    icon: "Cable",
    colorway: ["#141414", "#3d3d3d"],
    inStock: true,
    stockCount: 96,
    sku: "BFL-CBL-020",
  },
  {
    id: "15",
    slug: "obsidian-clear-case",
    name: "Obsidian Clear Guard Case",
    category: "Cases & Protection",
    price: 199,
    rating: 4.4,
    reviewCount: 118,
    badge: null,
    shortDescription: "Yellowing-resistant clear case with reinforced corners.",
    description:
      "A crystal-clear case built from anti-yellowing TPU that keeps your phone's original look on show, with air-cushion corners for genuine drop protection where it matters most.",
    features: [
      "Anti-yellowing TPU material",
      "Air-cushion reinforced corners",
      "Precision camera cutouts",
      "Wireless charging compatible",
      "Slim 1.2mm profile",
    ],
    icon: "ShieldHalf",
    colorway: ["#0a0a0a", "#4a4a4a"],
    inStock: false,
    stockCount: 0,
    sku: "BFL-PRO-019",
  },
  {
    id: "16",
    slug: "resonate-mini-speaker",
    name: "Resonate Mini Bluetooth Speaker",
    category: "Audio",
    price: 649,
    rating: 4.5,
    reviewCount: 143,
    badge: "New",
    shortDescription: "Pocket speaker with 12-hour battery and IP67 rating.",
    description:
      "Big, room-filling sound from a speaker that fits in one hand. IP67 dust and water resistance means it's just as happy by the pool as it is on a bookshelf, and 12 hours of playback keeps the party going.",
    features: [
      "360-degree sound with passive bass radiator",
      "IP67 dust & water resistant",
      "12-hour battery life",
      "Bluetooth 5.3 with 20m range",
      "Built-in speakerphone mic",
    ],
    icon: "Speaker",
    colorway: ["#050505", "#2c2c2c"],
    inStock: true,
    stockCount: 47,
    sku: "BFL-AUD-012",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.category === product.category && p.id !== product.id
  ).slice(0, count);
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat("en-ZA", {
    style: "currency",
    currency: "ZAR",
    minimumFractionDigits: 2,
  }).format(amount);
}
